payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

ekyna_payment_paypal:
    pattern: /payment/paypal-express-checkout
    defaults:
        _controller: EkynaPaymentBundle:Payment:paypalExpressCheckoutPayment
    requirements:
        _method: GET

ekyna_payment_done:
    pattern: /payment/done
    defaults:
        _controller: EkynaPaymentBundle:Payment:captureDone
    requirements:
        _method: GET