# Liip Imagine
liip_imagine:
    filter_sets:
        payment_method:
            quality: 70
            data_loader: local_image
            filters:
                thumbnail: { size: [145, 109], mode: outbound }
            post_processors:
                jpegoptim: {}