payum:
    security:
        token_storage:
            Ekyna\Bundle\PaymentBundle\Entity\PayumSecurityToken: { doctrine: orm }
    dynamic_gateways:
        sonata_admin: false
        config_storage:
            Ekyna\Bundle\PaymentBundle\Entity\Method: { doctrine: orm }
