winzou_state_machine:
    ekyna_payment:
        class:         Ekyna\Component\Sale\Payment\PaymentInterface
        property_path: state
        state_machine_class: Ekyna\Bundle\PaymentBundle\StateMachine\StateMachine
        states:
            new:        ~
            pending:    ~
            captured:  ~
            cancelled:  ~
            failed:     ~
            refunded:   ~
            authorized: ~
            suspended: ~
            expired: ~
            unknown:    ~
        transitions:
            hang:
                from: [new]
                to:   pending
            capture:
                from: [new, pending, authorized]
                to:   captured
            cancel:
                from: [new, pending]
                to:   cancelled
            fail:
                from: [new, pending, authorized]
                to:   failed
            refund:
                from: [captured]
                to:   refunded
            authorize:
                from: [new, pending]
                to:   authorized
            suspend:
                from: [pending, authorized]
                to:   suspended
            expire:
                from: [pending, authorized]
                to:   expired
            void:
                from: [new, pending]
                to:   unknown
